// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
            <SectionErrorBoundary name="about">
              <AboutMediaOverlay
                tag="O nama"
                title="Više od 20 godina iskustva"
                description="Instalacije Krznarić su obiteljski obrt s tradicijom. Naš cilj je pružiti vrhunsku uslugu koja će osigurati dugotrajnost vaših instalacija i mir u vašem domu."
                primaryButton={{ text: "Saznaj više", href: "#contact" }}
                imageSrc="http://img.b2bpic.net/free-photo/sanitary-technician-lying-sink_23-2147772221.jpg"
              />
            </SectionErrorBoundary>
          </div>
  );
}
