// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="Kontakt"
                text="Trebate vodoinstalatera u Zagrebu? Nazovite nas odmah za besplatnu procjenu."
                primaryButton={{ text: "098 208 195", href: "tel:098208195" }}
                secondaryButton={{ text: "Pošalji email", href: "mailto:info@krznaric.hr" }}
              />
            </SectionErrorBoundary>
          </div>
  );
}
