// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
            <SectionErrorBoundary name="faq">
              <FaqSimple
                tag="Pitanja"
                title="Česta pitanja"
                description="Evo odgovora na neka od vaših pitanja."
                items={[
                  { question: "Dostupni ste 0-24?", answer: "Da, za hitne intervencije smo dostupni non-stop." },
                  { question: "Radite li adaptacije?", answer: "Da, radimo kompletne adaptacije kupaonica." },
                  { question: "Kako dogovoriti termin?", answer: "Jednostavno nas nazovite na broj 098 208 195." },
                ]}
              />
            </SectionErrorBoundary>
          </div>
  );
}
