// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesMediaCarousel from '@/components/sections/features/FeaturesMediaCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
            <SectionErrorBoundary name="features">
              <FeaturesMediaCarousel
                tag="Naše usluge"
                title="Što sve radimo?"
                description="Od hitnih intervencija do kompletnih adaptacija, pokrivamo sve aspekte vodoinstalaterskih radova."
                items={[
                  { title: "Hitne intervencije", description: "Dostupni smo 0-24h za hitne popravke curenja i kvarova.", buttonIcon: "Zap", imageSrc: "http://img.b2bpic.net/free-photo/male-hands-with-wrench-turning-off-valves_169016-53780.jpg" },
                  { title: "Adaptacije kupaonica", description: "Kompletna montaža sanitarija i instalacija po principu ključ u ruke.", buttonIcon: "CheckCircle", imageSrc: "http://img.b2bpic.net/free-photo/matte-black-kitchen-faucet-sink-with-drying-rack-blue-kitchen-minimal-interior_169016-69329.jpg" },
                  { title: "Održavanje instalacija", description: "Redovno održavanje cijevi i provjera funkcionalnosti sustava.", buttonIcon: "Shield", imageSrc: "http://img.b2bpic.net/free-photo/asian-plumber-blue-overalls-clearing-blockage-drain_1098-17773.jpg" },
                  { title: "Odštopavanje odvoda", description: "Brzo i efikasno odštopavanje odvoda najmodernijim metodama.", buttonIcon: "ArrowRight", imageSrc: "http://img.b2bpic.net/free-photo/flexible-connector-different-wrenches_23-2147772264.jpg" },
                  { title: "Montaža bojlera", description: "Stručna ugradnja i servis svih vrsta bojlera.", buttonIcon: "Award", imageSrc: "http://img.b2bpic.net/free-photo/male-plumber-working-with-client-fix-kitchen-problems_23-2150990680.jpg" },
                  { title: "Instalacija vodovoda", description: "Polaganje novih instalacija vode za stambene prostore.", buttonIcon: "Star", imageSrc: "http://img.b2bpic.net/free-photo/side-view-woman-working-as-plumber_23-2150746391.jpg" },
                ]}
              />
            </SectionErrorBoundary>
          </div>
  );
}
