/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import AvatarGroup from "@/components/ui/AvatarGroup";

const primaryButton = {
  text: "Nazovi odmah",
  href: "tel:098208195"
};
const secondaryButton = {
  text: "Pošalji upit",
  href: "#contact"
};

type HeroOverlayProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  avatarsSrc?: string[];
  avatarsLabel?: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const HeroInline = () => {
  return (
    <section
      aria-label="Hero section"
      className="relative w-full h-svh overflow-hidden flex flex-col justify-end mb-20"
    >
      <HeroBackgroundSlot />
      <ImageOrVideo
        imageSrc={"http://img.b2bpic.net/free-photo/man-fixing-kitchen-sink_53876-13430.jpg"}
        className="absolute inset-0 w-full h-full object-cover rounded-none"
      />
      <div className="absolute inset-0 bg-black/50 z-[5]" aria-hidden="true" />

      <div
        className="absolute z-10 w-[150vw] h-[150vw] left-0 bottom-0 -translate-x-1/2 translate-y-1/2 backdrop-blur mask-[radial-gradient(circle,black_20%,transparent_70%)]"
        aria-hidden="true"
      />

      <div className="relative z-10 w-content-width mx-auto pb-10 md:pb-25">
        <div className="flex flex-col gap-3 w-full md:w-6/10 lg:w-1/2 xl:w-45/100 2xl:w-4/10">
          <div className="w-fit px-3 py-1 mb-1 text-sm card rounded">
            <p>{"Dostupni 0-24"}</p>
          </div>

          <TextAnimation
            text={"Vaš pouzdan vodoinstalater u Zagrebu"}
            variant="fade"
            gradientText={true}
            tag="h1"
            className="text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-white text-balance"
          />

          <TextAnimation
            text={"Brze, profesionalne i povoljne vodoinstalaterske usluge. Instalacije Krznarić rješava sve kvarove brzo i efikasno."}
            variant="fade"
            gradientText={false}
            tag="p"
            className="text-lg md:text-xl text-white leading-snug text-balance"
          />

          <div className="flex flex-wrap gap-3 mt-2 md:mt-3">
            <Button text={primaryButton.text} href={primaryButton.href} variant="primary"/>
            <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary"animationDelay={0.1} />
          </div>

          {undefined && undefined.length > 0 && (
            <div className="mt-3 md:mt-4">
              <AvatarGroup size="lg" labelClassName="text-primary-cta-text" />
            </div>
          )}
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
