// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlay from '@/components/sections/hero/HeroOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
            <SectionErrorBoundary name="hero">
              <HeroOverlay
                tag="Dostupni 0-24"
                title="Vaš pouzdan vodoinstalater u Zagrebu"
                description="Brze, profesionalne i povoljne vodoinstalaterske usluge. Instalacije Krznarić rješava sve kvarove brzo i efikasno."
                primaryButton={{ text: "Nazovi odmah", href: "tel:098208195" }}
                secondaryButton={{ text: "Pošalji upit", href: "#contact" }}
                imageSrc="http://img.b2bpic.net/free-photo/man-fixing-kitchen-sink_53876-13430.jpg"
              />
            </SectionErrorBoundary>
          </div>
  );
}
