// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
            <SectionErrorBoundary name="metrics">
              <MetricsIconCards
                tag="Rezultati"
                title="Brojke koje govore za nas"
                description="Više od dva desetljeća iskustva u pružanju vrhunskih usluga."
                metrics={[
                  { icon: "CheckCircle", title: "Zadovoljnih klijenata", value: "1000+" },
                  { icon: "Clock", title: "Godina iskustva", value: "20+" },
                  { icon: "Zap", title: "Hitnih intervencija", value: "500+" },
                ]}
              />
            </SectionErrorBoundary>
          </div>
  );
}
