// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
            <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
                tag="Recenzije"
                title="Što kažu naši klijenti"
                description="Zadovoljstvo naših klijenata nam je na prvom mjestu."
                testimonials={[
                  { name: "Filip Kurtić", role: "Klijent", quote: "Sve super, odlično odrađen posao, drži se dogovora.", imageSrc: "http://img.b2bpic.net/free-photo/close-up-portrait-handsome-middle-aged-man-with-beard-hairstyle-dressed-elegant-formal-suit-textured-dark-background-studio_613910-19909.jpg" },
                  { name: "Mihael Hacmanjek", role: "Klijent", quote: "Svaka čast! Pristojni i uredni. Preporučam!", imageSrc: "http://img.b2bpic.net/free-photo/happy-man-with-miniature-his-future-home_1149-759.jpg" },
                  { name: "Ivana Horvat", role: "Klijent", quote: "Brzi odaziv i kvalitetna usluga, sve pohvale.", imageSrc: "http://img.b2bpic.net/free-photo/hands-holding-word-customer_53876-30892.jpg" },
                  { name: "Marko Perić", role: "Klijent", quote: "Instalacije Krznarić su mi riješile hitan kvar u nedjelju.", imageSrc: "http://img.b2bpic.net/free-photo/portrait-sensual-curly-woman-smiles-pleasantly-holds-chin-expresses-positive-emotions-keeps-smiling-shows-white-teeth-wears-pink-knitted-sweater-has-beauty-face-healthy-skin-curly-hair_273609-42620.jpg" },
                  { name: "Ana Kovač", role: "Klijent", quote: "Izuzetno profesionalni i pedantni radnici.", imageSrc: "http://img.b2bpic.net/free-photo/indoor-image-optimistic-energetic-mature-businesswoman-with-short-blonde-hair-posing-stylish-office-interior-with-arms-folded-her-chest-looking-camera-with-confident-happy-smile_343059-2245.jpg" },
                ]}
              />
            </SectionErrorBoundary>
          </div>
  );
}
